(define (problem strips-gripper-x-1)
(:domain gripper-strips-typing)
(:objects
transportador
	n0 n1 n2 n3 n4
		gripper_1_left 
	location_deposito loc1 loc2 loc3 loc4 loc5 loc6 loc7 loc8 loc9 loc10 loc11 loc12 loc13 loc14 loc15 loc16 loc17 loc18 loc19 loc20 loc21 loc22 loc23 loc24 loc25 loc26 loc27 loc28 loc29 loc30 loc31 loc32 loc33 loc34 loc35 loc36 loc37 loc38 loc39 loc40 loc41 loc42 loc43 loc44 loc45 loc46 loc47 loc48 loc49 loc50 
	box1 box2 box3 box4 box5 box6 box7 box8 box9 box10 box11 box12 box13 box14 box15 box16 box17 box18 box19 box20 box21 box22 box23 box24 box25 box26 box27 box28 box29 box30 box31 box32 box33 box34 box35 box36 box37 box38 box39 box40 box41 box42 box43 box44 box45 box46 box47 box48 box49 box50 
	food medicine 
	person1 person2 person3 person4 person5 person6 person7 person8 person9 person10 person11 person12 person13 person14 person15 person16 person17 person18 person19 person20 person21 person22 person23 person24 person25 person26 person27 person28 person29 person30 person31 person32 person33 person34 person35 person36 person37 person38 person39 person40 person41 person42 person43 person44 person45 person46 person47 person48 person49 person50 
	
	)
(:init
	(siguiente n0 n1)
	(siguiente n1 n2)
	(siguiente n2 n3)
	(siguiente n3 n4)

	(carga-actual transportador n0)

	(transportador transportador)

	(transportador-not-carry transportador)

	(gripper gripper_1_left)

	(location location_deposito)
	(location loc1)
	(location loc2)
	(location loc3)
	(location loc4)
	(location loc5)
	(location loc6)
	(location loc7)
	(location loc8)
	(location loc9)
	(location loc10)
	(location loc11)
	(location loc12)
	(location loc13)
	(location loc14)
	(location loc15)
	(location loc16)
	(location loc17)
	(location loc18)
	(location loc19)
	(location loc20)
	(location loc21)
	(location loc22)
	(location loc23)
	(location loc24)
	(location loc25)
	(location loc26)
	(location loc27)
	(location loc28)
	(location loc29)
	(location loc30)
	(location loc31)
	(location loc32)
	(location loc33)
	(location loc34)
	(location loc35)
	(location loc36)
	(location loc37)
	(location loc38)
	(location loc39)
	(location loc40)
	(location loc41)
	(location loc42)
	(location loc43)
	(location loc44)
	(location loc45)
	(location loc46)
	(location loc47)
	(location loc48)
	(location loc49)
	(location loc50)

	(box box1)
	(box box2)
	(box box3)
	(box box4)
	(box box5)
	(box box6)
	(box box7)
	(box box8)
	(box box9)
	(box box10)
	(box box11)
	(box box12)
	(box box13)
	(box box14)
	(box box15)
	(box box16)
	(box box17)
	(box box18)
	(box box19)
	(box box20)
	(box box21)
	(box box22)
	(box box23)
	(box box24)
	(box box25)
	(box box26)
	(box box27)
	(box box28)
	(box box29)
	(box box30)
	(box box31)
	(box box32)
	(box box33)
	(box box34)
	(box box35)
	(box box36)
	(box box37)
	(box box38)
	(box box39)
	(box box40)
	(box box41)
	(box box42)
	(box box43)
	(box box44)
	(box box45)
	(box box46)
	(box box47)
	(box box48)
	(box box49)
	(box box50)

	(type food)
	(type medicine)

	(person person1)
	(person person2)
	(person person3)
	(person person4)
	(person person5)
	(person person6)
	(person person7)
	(person person8)
	(person person9)
	(person person10)
	(person person11)
	(person person12)
	(person person13)
	(person person14)
	(person person15)
	(person person16)
	(person person17)
	(person person18)
	(person person19)
	(person person20)
	(person person21)
	(person person22)
	(person person23)
	(person person24)
	(person person25)
	(person person26)
	(person person27)
	(person person28)
	(person person29)
	(person person30)
	(person person31)
	(person person32)
	(person person33)
	(person person34)
	(person person35)
	(person person36)
	(person person37)
	(person person38)
	(person person39)
	(person person40)
	(person person41)
	(person person42)
	(person person43)
	(person person44)
	(person person45)
	(person person46)
	(person person47)
	(person person48)
	(person person49)
	(person person50)

	(gripper-at gripper_1_left location_deposito)
	(free gripper_1_left)
	(transportador-at transportador location_deposito)

	(box-type box1 food)
	(box-type box2 medicine)
	(box-type box3 food)
	(box-type box4 medicine)
	(box-type box5 food)
	(box-type box6 medicine)
	(box-type box7 food)
	(box-type box8 medicine)
	(box-type box9 food)
	(box-type box10 medicine)
	(box-type box11 food)
	(box-type box12 medicine)
	(box-type box13 food)
	(box-type box14 medicine)
	(box-type box15 food)
	(box-type box16 medicine)
	(box-type box17 food)
	(box-type box18 medicine)
	(box-type box19 food)
	(box-type box20 medicine)
	(box-type box21 food)
	(box-type box22 medicine)
	(box-type box23 food)
	(box-type box24 medicine)
	(box-type box25 food)
	(box-type box26 medicine)
	(box-type box27 food)
	(box-type box28 medicine)
	(box-type box29 food)
	(box-type box30 medicine)
	(box-type box31 food)
	(box-type box32 medicine)
	(box-type box33 food)
	(box-type box34 medicine)
	(box-type box35 food)
	(box-type box36 medicine)
	(box-type box37 food)
	(box-type box38 medicine)
	(box-type box39 food)
	(box-type box40 medicine)
	(box-type box41 food)
	(box-type box42 medicine)
	(box-type box43 food)
	(box-type box44 medicine)
	(box-type box45 food)
	(box-type box46 medicine)
	(box-type box47 food)
	(box-type box48 medicine)
	(box-type box49 food)
	(box-type box50 medicine)

	(box-at box1 location_deposito)
	(box-at box2 location_deposito)
	(box-at box3 location_deposito)
	(box-at box4 location_deposito)
	(box-at box5 location_deposito)
	(box-at box6 location_deposito)
	(box-at box7 location_deposito)
	(box-at box8 location_deposito)
	(box-at box9 location_deposito)
	(box-at box10 location_deposito)
	(box-at box11 location_deposito)
	(box-at box12 location_deposito)
	(box-at box13 location_deposito)
	(box-at box14 location_deposito)
	(box-at box15 location_deposito)
	(box-at box16 location_deposito)
	(box-at box17 location_deposito)
	(box-at box18 location_deposito)
	(box-at box19 location_deposito)
	(box-at box20 location_deposito)
	(box-at box21 location_deposito)
	(box-at box22 location_deposito)
	(box-at box23 location_deposito)
	(box-at box24 location_deposito)
	(box-at box25 location_deposito)
	(box-at box26 location_deposito)
	(box-at box27 location_deposito)
	(box-at box28 location_deposito)
	(box-at box29 location_deposito)
	(box-at box30 location_deposito)
	(box-at box31 location_deposito)
	(box-at box32 location_deposito)
	(box-at box33 location_deposito)
	(box-at box34 location_deposito)
	(box-at box35 location_deposito)
	(box-at box36 location_deposito)
	(box-at box37 location_deposito)
	(box-at box38 location_deposito)
	(box-at box39 location_deposito)
	(box-at box40 location_deposito)
	(box-at box41 location_deposito)
	(box-at box42 location_deposito)
	(box-at box43 location_deposito)
	(box-at box44 location_deposito)
	(box-at box45 location_deposito)
	(box-at box46 location_deposito)
	(box-at box47 location_deposito)
	(box-at box48 location_deposito)
	(box-at box49 location_deposito)
	(box-at box50 location_deposito)

	(person-at person1 loc11)
	(person-at person2 loc20)
	(person-at person3 loc45)
	(person-at person4 loc39)
	(person-at person5 loc8)
	(person-at person6 loc41)
	(person-at person7 loc33)
	(person-at person8 loc33)
	(person-at person9 loc24)
	(person-at person10 loc15)
	(person-at person11 loc45)
	(person-at person12 loc20)
	(person-at person13 loc19)
	(person-at person14 loc36)
	(person-at person15 loc21)
	(person-at person16 loc28)
	(person-at person17 loc34)
	(person-at person18 loc5)
	(person-at person19 loc10)
	(person-at person20 loc43)
	(person-at person21 loc3)
	(person-at person22 loc47)
	(person-at person23 loc4)
	(person-at person24 loc23)
	(person-at person25 loc38)
	(person-at person26 loc17)
	(person-at person27 loc24)
	(person-at person28 loc17)
	(person-at person29 loc15)
	(person-at person30 loc20)
	(person-at person31 loc6)
	(person-at person32 loc6)
	(person-at person33 loc40)
	(person-at person34 loc38)
	(person-at person35 loc17)
	(person-at person36 loc7)
	(person-at person37 loc41)
	(person-at person38 loc39)
	(person-at person39 loc45)
	(person-at person40 loc35)
	(person-at person41 loc16)
	(person-at person42 loc26)
	(person-at person43 loc49)
	(person-at person44 loc4)
	(person-at person45 loc42)
	(person-at person46 loc12)
	(person-at person47 loc34)
	(person-at person48 loc25)
	(person-at person49 loc16)
	(person-at person50 loc12)

	(person-dont-have person1 food)
	(person-have person1 medicine)
	(person-have person2 food)
	(person-dont-have person2 medicine)
	(person-dont-have person3 food)
	(person-have person3 medicine)
	(person-have person4 food)
	(person-dont-have person4 medicine)
	(person-dont-have person5 food)
	(person-have person5 medicine)
	(person-have person6 food)
	(person-dont-have person6 medicine)
	(person-dont-have person7 food)
	(person-have person7 medicine)
	(person-have person8 food)
	(person-dont-have person8 medicine)
	(person-dont-have person9 food)
	(person-have person9 medicine)
	(person-have person10 food)
	(person-dont-have person10 medicine)
	(person-dont-have person11 food)
	(person-have person11 medicine)
	(person-have person12 food)
	(person-dont-have person12 medicine)
	(person-dont-have person13 food)
	(person-have person13 medicine)
	(person-have person14 food)
	(person-dont-have person14 medicine)
	(person-dont-have person15 food)
	(person-have person15 medicine)
	(person-have person16 food)
	(person-dont-have person16 medicine)
	(person-dont-have person17 food)
	(person-have person17 medicine)
	(person-have person18 food)
	(person-dont-have person18 medicine)
	(person-dont-have person19 food)
	(person-have person19 medicine)
	(person-have person20 food)
	(person-dont-have person20 medicine)
	(person-dont-have person21 food)
	(person-have person21 medicine)
	(person-have person22 food)
	(person-dont-have person22 medicine)
	(person-dont-have person23 food)
	(person-have person23 medicine)
	(person-have person24 food)
	(person-dont-have person24 medicine)
	(person-dont-have person25 food)
	(person-have person25 medicine)
	(person-have person26 food)
	(person-dont-have person26 medicine)
	(person-dont-have person27 food)
	(person-have person27 medicine)
	(person-have person28 food)
	(person-dont-have person28 medicine)
	(person-dont-have person29 food)
	(person-have person29 medicine)
	(person-have person30 food)
	(person-dont-have person30 medicine)
	(person-dont-have person31 food)
	(person-have person31 medicine)
	(person-have person32 food)
	(person-dont-have person32 medicine)
	(person-dont-have person33 food)
	(person-have person33 medicine)
	(person-have person34 food)
	(person-dont-have person34 medicine)
	(person-dont-have person35 food)
	(person-have person35 medicine)
	(person-have person36 food)
	(person-dont-have person36 medicine)
	(person-dont-have person37 food)
	(person-have person37 medicine)
	(person-have person38 food)
	(person-dont-have person38 medicine)
	(person-dont-have person39 food)
	(person-have person39 medicine)
	(person-have person40 food)
	(person-dont-have person40 medicine)
	(person-dont-have person41 food)
	(person-have person41 medicine)
	(person-have person42 food)
	(person-dont-have person42 medicine)
	(person-dont-have person43 food)
	(person-have person43 medicine)
	(person-have person44 food)
	(person-dont-have person44 medicine)
	(person-dont-have person45 food)
	(person-have person45 medicine)
	(person-have person46 food)
	(person-dont-have person46 medicine)
	(person-dont-have person47 food)
	(person-have person47 medicine)
	(person-have person48 food)
	(person-dont-have person48 medicine)
	(person-dont-have person49 food)
	(person-have person49 medicine)
	(person-have person50 food)
	(person-dont-have person50 medicine)

)
(:goal (and
	(person-have person1 food)
	(person-have person1 medicine)
	(person-have person2 food)
	(person-have person2 medicine)
	(person-have person3 food)
	(person-have person3 medicine)
	(person-have person4 food)
	(person-have person4 medicine)
	(person-have person5 food)
	(person-have person5 medicine)
	(person-have person6 food)
	(person-have person6 medicine)
	(person-have person7 food)
	(person-have person7 medicine)
	(person-have person8 food)
	(person-have person8 medicine)
	(person-have person9 food)
	(person-have person9 medicine)
	(person-have person10 food)
	(person-have person10 medicine)
	(person-have person11 food)
	(person-have person11 medicine)
	(person-have person12 food)
	(person-have person12 medicine)
	(person-have person13 food)
	(person-have person13 medicine)
	(person-have person14 food)
	(person-have person14 medicine)
	(person-have person15 food)
	(person-have person15 medicine)
	(person-have person16 food)
	(person-have person16 medicine)
	(person-have person17 food)
	(person-have person17 medicine)
	(person-have person18 food)
	(person-have person18 medicine)
	(person-have person19 food)
	(person-have person19 medicine)
	(person-have person20 food)
	(person-have person20 medicine)
	(person-have person21 food)
	(person-have person21 medicine)
	(person-have person22 food)
	(person-have person22 medicine)
	(person-have person23 food)
	(person-have person23 medicine)
	(person-have person24 food)
	(person-have person24 medicine)
	(person-have person25 food)
	(person-have person25 medicine)
	(person-have person26 food)
	(person-have person26 medicine)
	(person-have person27 food)
	(person-have person27 medicine)
	(person-have person28 food)
	(person-have person28 medicine)
	(person-have person29 food)
	(person-have person29 medicine)
	(person-have person30 food)
	(person-have person30 medicine)
	(person-have person31 food)
	(person-have person31 medicine)
	(person-have person32 food)
	(person-have person32 medicine)
	(person-have person33 food)
	(person-have person33 medicine)
	(person-have person34 food)
	(person-have person34 medicine)
	(person-have person35 food)
	(person-have person35 medicine)
	(person-have person36 food)
	(person-have person36 medicine)
	(person-have person37 food)
	(person-have person37 medicine)
	(person-have person38 food)
	(person-have person38 medicine)
	(person-have person39 food)
	(person-have person39 medicine)
	(person-have person40 food)
	(person-have person40 medicine)
	(person-have person41 food)
	(person-have person41 medicine)
	(person-have person42 food)
	(person-have person42 medicine)
	(person-have person43 food)
	(person-have person43 medicine)
	(person-have person44 food)
	(person-have person44 medicine)
	(person-have person45 food)
	(person-have person45 medicine)
	(person-have person46 food)
	(person-have person46 medicine)
	(person-have person47 food)
	(person-have person47 medicine)
	(person-have person48 food)
	(person-have person48 medicine)
	(person-have person49 food)
	(person-have person49 medicine)
	(person-have person50 food)
	(person-have person50 medicine)
	))
)