(define (problem strips-gripper-x-1)
(:domain gripper-strips-typing)
(:objects
transportador
	n0 n1 n2 n3 n4
		gripper_1_left 
	location_deposito loc1 loc2 loc3 loc4 loc5 loc6 loc7 loc8 loc9 loc10 loc11 loc12 loc13 loc14 loc15 loc16 loc17 loc18 loc19 loc20 
	box1 box2 box3 box4 box5 box6 box7 box8 box9 box10 box11 box12 box13 box14 box15 box16 box17 box18 box19 box20 
	food medicine 
	person1 person2 person3 person4 person5 person6 person7 person8 person9 person10 person11 person12 person13 person14 person15 person16 person17 person18 person19 person20 
	
	)
(:init
	(siguiente n0 n1)
	(siguiente n1 n2)
	(siguiente n2 n3)
	(siguiente n3 n4)

	(carga-actual transportador n0)

	(transportador transportador)

	(transportador-not-carry transportador)

	(gripper gripper_1_left)

	(location location_deposito)
	(location loc1)
	(location loc2)
	(location loc3)
	(location loc4)
	(location loc5)
	(location loc6)
	(location loc7)
	(location loc8)
	(location loc9)
	(location loc10)
	(location loc11)
	(location loc12)
	(location loc13)
	(location loc14)
	(location loc15)
	(location loc16)
	(location loc17)
	(location loc18)
	(location loc19)
	(location loc20)

	(box box1)
	(box box2)
	(box box3)
	(box box4)
	(box box5)
	(box box6)
	(box box7)
	(box box8)
	(box box9)
	(box box10)
	(box box11)
	(box box12)
	(box box13)
	(box box14)
	(box box15)
	(box box16)
	(box box17)
	(box box18)
	(box box19)
	(box box20)

	(type food)
	(type medicine)

	(person person1)
	(person person2)
	(person person3)
	(person person4)
	(person person5)
	(person person6)
	(person person7)
	(person person8)
	(person person9)
	(person person10)
	(person person11)
	(person person12)
	(person person13)
	(person person14)
	(person person15)
	(person person16)
	(person person17)
	(person person18)
	(person person19)
	(person person20)

	(gripper-at gripper_1_left location_deposito)
	(free gripper_1_left)
	(transportador-at transportador location_deposito)

	(box-type box1 food)
	(box-type box2 medicine)
	(box-type box3 food)
	(box-type box4 medicine)
	(box-type box5 food)
	(box-type box6 medicine)
	(box-type box7 food)
	(box-type box8 medicine)
	(box-type box9 food)
	(box-type box10 medicine)
	(box-type box11 food)
	(box-type box12 medicine)
	(box-type box13 food)
	(box-type box14 medicine)
	(box-type box15 food)
	(box-type box16 medicine)
	(box-type box17 food)
	(box-type box18 medicine)
	(box-type box19 food)
	(box-type box20 medicine)

	(box-at box1 location_deposito)
	(box-at box2 location_deposito)
	(box-at box3 location_deposito)
	(box-at box4 location_deposito)
	(box-at box5 location_deposito)
	(box-at box6 location_deposito)
	(box-at box7 location_deposito)
	(box-at box8 location_deposito)
	(box-at box9 location_deposito)
	(box-at box10 location_deposito)
	(box-at box11 location_deposito)
	(box-at box12 location_deposito)
	(box-at box13 location_deposito)
	(box-at box14 location_deposito)
	(box-at box15 location_deposito)
	(box-at box16 location_deposito)
	(box-at box17 location_deposito)
	(box-at box18 location_deposito)
	(box-at box19 location_deposito)
	(box-at box20 location_deposito)

	(person-at person1 loc13)
	(person-at person2 loc2)
	(person-at person3 loc1)
	(person-at person4 loc8)
	(person-at person5 loc5)
	(person-at person6 loc19)
	(person-at person7 loc9)
	(person-at person8 loc17)
	(person-at person9 loc4)
	(person-at person10 loc2)
	(person-at person11 loc13)
	(person-at person12 loc11)
	(person-at person13 loc13)
	(person-at person14 loc14)
	(person-at person15 loc11)
	(person-at person16 loc18)
	(person-at person17 loc19)
	(person-at person18 loc19)
	(person-at person19 loc17)
	(person-at person20 loc12)

	(person-dont-have person1 food)
	(person-have person1 medicine)
	(person-have person2 food)
	(person-dont-have person2 medicine)
	(person-dont-have person3 food)
	(person-have person3 medicine)
	(person-have person4 food)
	(person-dont-have person4 medicine)
	(person-dont-have person5 food)
	(person-have person5 medicine)
	(person-have person6 food)
	(person-dont-have person6 medicine)
	(person-dont-have person7 food)
	(person-have person7 medicine)
	(person-have person8 food)
	(person-dont-have person8 medicine)
	(person-dont-have person9 food)
	(person-have person9 medicine)
	(person-have person10 food)
	(person-dont-have person10 medicine)
	(person-dont-have person11 food)
	(person-have person11 medicine)
	(person-have person12 food)
	(person-dont-have person12 medicine)
	(person-dont-have person13 food)
	(person-have person13 medicine)
	(person-have person14 food)
	(person-dont-have person14 medicine)
	(person-dont-have person15 food)
	(person-have person15 medicine)
	(person-have person16 food)
	(person-dont-have person16 medicine)
	(person-dont-have person17 food)
	(person-have person17 medicine)
	(person-have person18 food)
	(person-dont-have person18 medicine)
	(person-dont-have person19 food)
	(person-have person19 medicine)
	(person-have person20 food)
	(person-dont-have person20 medicine)

)
(:goal (and
	(person-have person1 food)
	(person-have person1 medicine)
	(person-have person2 food)
	(person-have person2 medicine)
	(person-have person3 food)
	(person-have person3 medicine)
	(person-have person4 food)
	(person-have person4 medicine)
	(person-have person5 food)
	(person-have person5 medicine)
	(person-have person6 food)
	(person-have person6 medicine)
	(person-have person7 food)
	(person-have person7 medicine)
	(person-have person8 food)
	(person-have person8 medicine)
	(person-have person9 food)
	(person-have person9 medicine)
	(person-have person10 food)
	(person-have person10 medicine)
	(person-have person11 food)
	(person-have person11 medicine)
	(person-have person12 food)
	(person-have person12 medicine)
	(person-have person13 food)
	(person-have person13 medicine)
	(person-have person14 food)
	(person-have person14 medicine)
	(person-have person15 food)
	(person-have person15 medicine)
	(person-have person16 food)
	(person-have person16 medicine)
	(person-have person17 food)
	(person-have person17 medicine)
	(person-have person18 food)
	(person-have person18 medicine)
	(person-have person19 food)
	(person-have person19 medicine)
	(person-have person20 food)
	(person-have person20 medicine)
	))
)