(define (problem strips-gripper-x-1)
(:domain gripper-strips-typing)
(:objects
	gripper1 	gripper2 	gripper3 gripper4 
	location_deposito loc1 loc2 loc3 loc4 loc5 loc6 loc7 loc8 loc9 loc10 loc11 loc12 loc13 loc14 loc15 loc16 loc17 loc18 loc19 loc20 loc21 loc22 loc23 loc24 loc25 loc26 loc27 loc28 loc29 loc30 loc31 loc32 loc33 loc34 loc35 loc36 loc37 loc38 loc39 loc40 
	box1 box2 box3 box4 box5 box6 box7 box8 box9 box10 box11 box12 box13 box14 box15 box16 box17 box18 box19 box20 box21 box22 box23 box24 box25 box26 box27 box28 box29 box30 box31 box32 box33 box34 box35 box36 box37 box38 box39 box40 
	food medicine 
	person1 person2 person3 person4 person5 person6 person7 person8 person9 person10 person11 person12 person13 person14 person15 person16 person17 person18 person19 person20 person21 person22 person23 person24 person25 person26 person27 person28 person29 person30 person31 person32 person33 person34 person35 person36 person37 person38 person39 person40 
	
	)
(:init
	(gripper gripper1)
	(gripper gripper2)
	(gripper gripper3)
	(gripper gripper4)

	(location location_deposito)
	(location loc1)
	(location loc2)
	(location loc3)
	(location loc4)
	(location loc5)
	(location loc6)
	(location loc7)
	(location loc8)
	(location loc9)
	(location loc10)
	(location loc11)
	(location loc12)
	(location loc13)
	(location loc14)
	(location loc15)
	(location loc16)
	(location loc17)
	(location loc18)
	(location loc19)
	(location loc20)
	(location loc21)
	(location loc22)
	(location loc23)
	(location loc24)
	(location loc25)
	(location loc26)
	(location loc27)
	(location loc28)
	(location loc29)
	(location loc30)
	(location loc31)
	(location loc32)
	(location loc33)
	(location loc34)
	(location loc35)
	(location loc36)
	(location loc37)
	(location loc38)
	(location loc39)
	(location loc40)

	(box box1)
	(box box2)
	(box box3)
	(box box4)
	(box box5)
	(box box6)
	(box box7)
	(box box8)
	(box box9)
	(box box10)
	(box box11)
	(box box12)
	(box box13)
	(box box14)
	(box box15)
	(box box16)
	(box box17)
	(box box18)
	(box box19)
	(box box20)
	(box box21)
	(box box22)
	(box box23)
	(box box24)
	(box box25)
	(box box26)
	(box box27)
	(box box28)
	(box box29)
	(box box30)
	(box box31)
	(box box32)
	(box box33)
	(box box34)
	(box box35)
	(box box36)
	(box box37)
	(box box38)
	(box box39)
	(box box40)

	(type food)
	(type medicine)

	(person person1)
	(person person2)
	(person person3)
	(person person4)
	(person person5)
	(person person6)
	(person person7)
	(person person8)
	(person person9)
	(person person10)
	(person person11)
	(person person12)
	(person person13)
	(person person14)
	(person person15)
	(person person16)
	(person person17)
	(person person18)
	(person person19)
	(person person20)
	(person person21)
	(person person22)
	(person person23)
	(person person24)
	(person person25)
	(person person26)
	(person person27)
	(person person28)
	(person person29)
	(person person30)
	(person person31)
	(person person32)
	(person person33)
	(person person34)
	(person person35)
	(person person36)
	(person person37)
	(person person38)
	(person person39)
	(person person40)

	(gripper-at gripper1 location_deposito)
	(gripper-at gripper2 location_deposito)
	(gripper-at gripper3 location_deposito)
	(gripper-at gripper4 location_deposito)

	(free gripper1)
	(free gripper2)
	(free gripper3)
	(free gripper4)

	(gripper-group gripper1 gripper2 gripper3 gripper4)

	(box-type box1 food)
	(box-type box2 medicine)
	(box-type box3 food)
	(box-type box4 medicine)
	(box-type box5 food)
	(box-type box6 medicine)
	(box-type box7 food)
	(box-type box8 medicine)
	(box-type box9 food)
	(box-type box10 medicine)
	(box-type box11 food)
	(box-type box12 medicine)
	(box-type box13 food)
	(box-type box14 medicine)
	(box-type box15 food)
	(box-type box16 medicine)
	(box-type box17 food)
	(box-type box18 medicine)
	(box-type box19 food)
	(box-type box20 medicine)
	(box-type box21 food)
	(box-type box22 medicine)
	(box-type box23 food)
	(box-type box24 medicine)
	(box-type box25 food)
	(box-type box26 medicine)
	(box-type box27 food)
	(box-type box28 medicine)
	(box-type box29 food)
	(box-type box30 medicine)
	(box-type box31 food)
	(box-type box32 medicine)
	(box-type box33 food)
	(box-type box34 medicine)
	(box-type box35 food)
	(box-type box36 medicine)
	(box-type box37 food)
	(box-type box38 medicine)
	(box-type box39 food)
	(box-type box40 medicine)

	(box-at box1 location_deposito)
	(box-at box2 location_deposito)
	(box-at box3 location_deposito)
	(box-at box4 location_deposito)
	(box-at box5 location_deposito)
	(box-at box6 location_deposito)
	(box-at box7 location_deposito)
	(box-at box8 location_deposito)
	(box-at box9 location_deposito)
	(box-at box10 location_deposito)
	(box-at box11 location_deposito)
	(box-at box12 location_deposito)
	(box-at box13 location_deposito)
	(box-at box14 location_deposito)
	(box-at box15 location_deposito)
	(box-at box16 location_deposito)
	(box-at box17 location_deposito)
	(box-at box18 location_deposito)
	(box-at box19 location_deposito)
	(box-at box20 location_deposito)
	(box-at box21 location_deposito)
	(box-at box22 location_deposito)
	(box-at box23 location_deposito)
	(box-at box24 location_deposito)
	(box-at box25 location_deposito)
	(box-at box26 location_deposito)
	(box-at box27 location_deposito)
	(box-at box28 location_deposito)
	(box-at box29 location_deposito)
	(box-at box30 location_deposito)
	(box-at box31 location_deposito)
	(box-at box32 location_deposito)
	(box-at box33 location_deposito)
	(box-at box34 location_deposito)
	(box-at box35 location_deposito)
	(box-at box36 location_deposito)
	(box-at box37 location_deposito)
	(box-at box38 location_deposito)
	(box-at box39 location_deposito)
	(box-at box40 location_deposito)

	(person-at person1 loc34)
	(person-at person2 loc3)
	(person-at person3 loc7)
	(person-at person4 loc23)
	(person-at person5 loc18)
	(person-at person6 loc39)
	(person-at person7 loc39)
	(person-at person8 loc7)
	(person-at person9 loc19)
	(person-at person10 loc13)
	(person-at person11 loc20)
	(person-at person12 loc21)
	(person-at person13 loc24)
	(person-at person14 loc22)
	(person-at person15 loc27)
	(person-at person16 loc12)
	(person-at person17 loc26)
	(person-at person18 loc14)
	(person-at person19 loc38)
	(person-at person20 loc14)
	(person-at person21 loc33)
	(person-at person22 loc37)
	(person-at person23 loc7)
	(person-at person24 loc34)
	(person-at person25 loc25)
	(person-at person26 loc11)
	(person-at person27 loc19)
	(person-at person28 loc17)
	(person-at person29 loc6)
	(person-at person30 loc4)
	(person-at person31 loc8)
	(person-at person32 loc5)
	(person-at person33 loc38)
	(person-at person34 loc27)
	(person-at person35 loc11)
	(person-at person36 loc6)
	(person-at person37 loc24)
	(person-at person38 loc16)
	(person-at person39 loc8)
	(person-at person40 loc31)

	(person-doesnt-have person1 food)
	(person-has person1 medicine)
	(person-has person2 food)
	(person-doesnt-have person2 medicine)
	(person-doesnt-have person3 food)
	(person-has person3 medicine)
	(person-has person4 food)
	(person-doesnt-have person4 medicine)
	(person-doesnt-have person5 food)
	(person-has person5 medicine)
	(person-has person6 food)
	(person-doesnt-have person6 medicine)
	(person-doesnt-have person7 food)
	(person-has person7 medicine)
	(person-has person8 food)
	(person-doesnt-have person8 medicine)
	(person-doesnt-have person9 food)
	(person-has person9 medicine)
	(person-has person10 food)
	(person-doesnt-have person10 medicine)
	(person-doesnt-have person11 food)
	(person-has person11 medicine)
	(person-has person12 food)
	(person-doesnt-have person12 medicine)
	(person-doesnt-have person13 food)
	(person-has person13 medicine)
	(person-has person14 food)
	(person-doesnt-have person14 medicine)
	(person-doesnt-have person15 food)
	(person-has person15 medicine)
	(person-has person16 food)
	(person-doesnt-have person16 medicine)
	(person-doesnt-have person17 food)
	(person-has person17 medicine)
	(person-has person18 food)
	(person-doesnt-have person18 medicine)
	(person-doesnt-have person19 food)
	(person-has person19 medicine)
	(person-has person20 food)
	(person-doesnt-have person20 medicine)
	(person-doesnt-have person21 food)
	(person-has person21 medicine)
	(person-has person22 food)
	(person-doesnt-have person22 medicine)
	(person-doesnt-have person23 food)
	(person-has person23 medicine)
	(person-has person24 food)
	(person-doesnt-have person24 medicine)
	(person-doesnt-have person25 food)
	(person-has person25 medicine)
	(person-has person26 food)
	(person-doesnt-have person26 medicine)
	(person-doesnt-have person27 food)
	(person-has person27 medicine)
	(person-has person28 food)
	(person-doesnt-have person28 medicine)
	(person-doesnt-have person29 food)
	(person-has person29 medicine)
	(person-has person30 food)
	(person-doesnt-have person30 medicine)
	(person-doesnt-have person31 food)
	(person-has person31 medicine)
	(person-has person32 food)
	(person-doesnt-have person32 medicine)
	(person-doesnt-have person33 food)
	(person-has person33 medicine)
	(person-has person34 food)
	(person-doesnt-have person34 medicine)
	(person-doesnt-have person35 food)
	(person-has person35 medicine)
	(person-has person36 food)
	(person-doesnt-have person36 medicine)
	(person-doesnt-have person37 food)
	(person-has person37 medicine)
	(person-has person38 food)
	(person-doesnt-have person38 medicine)
	(person-doesnt-have person39 food)
	(person-has person39 medicine)
	(person-has person40 food)
	(person-doesnt-have person40 medicine)

)
(:goal (and
	(person-has person1 food)
	(person-has person1 medicine)
	(person-has person2 food)
	(person-has person2 medicine)
	(person-has person3 food)
	(person-has person3 medicine)
	(person-has person4 food)
	(person-has person4 medicine)
	(person-has person5 food)
	(person-has person5 medicine)
	(person-has person6 food)
	(person-has person6 medicine)
	(person-has person7 food)
	(person-has person7 medicine)
	(person-has person8 food)
	(person-has person8 medicine)
	(person-has person9 food)
	(person-has person9 medicine)
	(person-has person10 food)
	(person-has person10 medicine)
	(person-has person11 food)
	(person-has person11 medicine)
	(person-has person12 food)
	(person-has person12 medicine)
	(person-has person13 food)
	(person-has person13 medicine)
	(person-has person14 food)
	(person-has person14 medicine)
	(person-has person15 food)
	(person-has person15 medicine)
	(person-has person16 food)
	(person-has person16 medicine)
	(person-has person17 food)
	(person-has person17 medicine)
	(person-has person18 food)
	(person-has person18 medicine)
	(person-has person19 food)
	(person-has person19 medicine)
	(person-has person20 food)
	(person-has person20 medicine)
	(person-has person21 food)
	(person-has person21 medicine)
	(person-has person22 food)
	(person-has person22 medicine)
	(person-has person23 food)
	(person-has person23 medicine)
	(person-has person24 food)
	(person-has person24 medicine)
	(person-has person25 food)
	(person-has person25 medicine)
	(person-has person26 food)
	(person-has person26 medicine)
	(person-has person27 food)
	(person-has person27 medicine)
	(person-has person28 food)
	(person-has person28 medicine)
	(person-has person29 food)
	(person-has person29 medicine)
	(person-has person30 food)
	(person-has person30 medicine)
	(person-has person31 food)
	(person-has person31 medicine)
	(person-has person32 food)
	(person-has person32 medicine)
	(person-has person33 food)
	(person-has person33 medicine)
	(person-has person34 food)
	(person-has person34 medicine)
	(person-has person35 food)
	(person-has person35 medicine)
	(person-has person36 food)
	(person-has person36 medicine)
	(person-has person37 food)
	(person-has person37 medicine)
	(person-has person38 food)
	(person-has person38 medicine)
	(person-has person39 food)
	(person-has person39 medicine)
	(person-has person40 food)
	(person-has person40 medicine)
	))
)
